### ISSUE TITLE
[Bug] Bumpy install process; not geared for windows machines

### ISSUE THREAD

**Issue by SeanKilleen** [creativetimofficial/ct-nextjs-material-kit-pro#25]
### Version
1.2.0
### Reproduction link
It's the out of the box ZIP file.
### Operating System
Windows 11
### Device
Dell XPS 15
### Browser & Version
N/A
### Steps to reproduce
* Download the ZIP file of the theme
* Extract zip file into a folder
* Run npm install:clean or npm install
### What is expected?
Things are installed and I can run the app
### What is actually happening?
npm install:clean fails on windows because it uses the `rm -rf` command which is not a valid command on windows. npm install fails because of an issue with gyp installing node-sass. Updating the version of node-sass from v5 to v6 appears to break a rule somewhere and then fails for that reason. 

---
### Solution
For the issue with install:clean, you may want to create a separate command for windows users that uses a natively available command; alternately, I think some projects previously made use of the rimraf package for this, though my memory is shaky there.
### Additional comments
Surprised to see how out of date some of the libraries are in the theme. I'd expect a purchased product to be using the latest libraries for a fresh start, not versions from a year ago; or at least kept up with the latest bugfix/patch releases. Was hoping to use this product to give myself a jump start; instead I had to spend time trying to fix it.

**Comment by sajadevo** [comment]
**Hi @SeanKilleen**

Thanks for using our product, the `npm install:clean` is not working its only for the linux based machines and related to the next issue please run the following commands in order to fix it:
1. Uninstall node-sass: `npm un node-sass`
2. Install sass: `npm i sass`
3. On the package.json replace all the node-sass commands with sass.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by sajadevo** [comment]
The issue is fixed for the new version of the product (v1.2.1) please update to the latest version to get the fixed version of the product.

Regards,
Sajad
