### ISSUE TITLE
Login >960 wrong sizing

### ISSUE THREAD

**Issue by wortkotze** [creativetimofficial/ct-nextjs-material-kit-pro#4]
1. open https://demos.creative-tim.com/nextjs-material-kit-pro/login

screensize >960 login div is sized too small

https://ibb.co/NypyT0r
https://ibb.co/Y3jjrc9

thx for checking 

Device: Mac / Chrome / Safari

**Comment by EINazare** [comment]
Hello there, @wortkotze ,

Thank you for your interest in working with our products.
This is because of the 
```
            <GridItem xs={12} sm={8} md={4}>
```
From inside this file: `pages/login.js`.
The only way to correct this would be to delete the wrapping GridItem (see above code) of the Card, and change the Card render from:
```
              <Card>
```
To:
```
              <Card style={{maxWidth: "300px"}}>
```
In our live preview, we will leave it like so, to showcase that on different breakpoints you can have different displays.

Since this issue does not comply with our rules, we will close it, please take a look at the bellow comment:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/nextjs-material-kit-pro

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

Best,
Manu
