### ISSUE TITLE
[Bug] Next.js 9.3 - Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`.

### ISSUE THREAD

**Issue by terchris** [creativetimofficial/ct-nextjs-material-kit-pro#6]
### Version
1.0
### Reproduction link
https://github.com/zeit/next.js/blob/master/errors/opt-out-auto-static-optimization.md
### Operating System
Mac
### Device
mac
### Browser & Version
any
### Steps to reproduce
npm run build
### What is expected?
After updating to nextjs version 9.3 there are some problems. nextjs has implemented Next-gen Static Site Generation (SSG) Support
and the getInitialProps is replaced by new functionality.

### What is actually happening?
The error message is 
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`.
Read more: https://err.sh/next.js/opt-out-auto-static-optimization

---
### Solution
Update the NextJS Material Kit PRO to reflect changes in nextjs 9.3

**Comment by EINazare** [comment]
Hello there, @terchris ,

Please keep our version of NextJS, and I'll try to make an update next week on this product.

Best,
Manu

**Comment by terchris** [comment]
Hi @EINazare 
I need some update on the progress of updating to Next.js 9.3 
I reported it a month ago. So far I have used development mode and that is just fine for development. 
But now I need to deploy, so I need to be able to use the pre rendering functionality.
 
Regards
Terje

**Comment by EINazare** [comment]
Hello there, @terchris ,

Sorry for this delay in my response, I did not have internet due to the COVID-19 situation, and was not able to reach to any of my colleagues to give you a response.
Here is the Card for this product:
![Screen Shot 2020-04-24 at 10 16 42 AM](https://user-images.githubusercontent.com/26245512/80185372-e654b380-8614-11ea-9086-fc0be35e62f9.png)

As you can see, the updated version will be uploaded on 1st of May.

Best,
Manu
