### ISSUE TITLE
[Bug] Loading page content is not getting away from the page, it keeps hanging on top of the page

### ISSUE THREAD

**Issue by pramodberwal** [creativetimofficial/ct-nextjs-material-kit-pro#9]
### Version
nextjs-material-kit-pro-v1.1.0
### Reproduction link
http://localhost:3000/academics/class
### Operating System
Windows
### Device
Laptop
### Browser & Version
Version 83.0.4103.106
### Steps to reproduce
Create a link to a page using next/link, lets say you have three pages
Page 1  ( on page I have a link like <Link> <a> To Page 2 </a> </Link>)
Page 2 - on page 2 redirect to page 3 like router.push('/page3')
Page 3 - Issue is here content loading is not being loaded successfully

Now you click on To Page 3 link if render page 3 but with content loading progress at the top shown in the attached image

### What is expected?
Page 3 should be loaded successfully
### What is actually happening?
Content loading is being displayed on the page forever with following error in the console log
index.js:1 Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.

---
### Solution
No Idea

**Comment by EINazare** [comment]
Hello there, @pramodberwal ,

Thank you for your interest in working with our products.
We've checked your issue, and it seems that we do not encounter your problem as well, so our best guess at this moment, is that the steps you have provided us:
```
Create a link to a page using next/link, lets say you have three pages
Page 1 ( on page I have a link like To Page 2 )
Page 2 - on page 2 redirect to page 3 like router.push('/page3')
Page 3 - Issue is here content loading is not being loaded successfully

Now you click on To Page 3 link if render page 3 but with content loading progress at the top shown in the attached image
```
Are incomplete, i.e. you have done further changes to the product.

Please provide us with the following video:
* Download the product (we need to see that you download and use a fresh copy of the product)
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Create new page
* Create link to new page
* Navigate to new page
* Showcase the issue

If you do not want to share the video here, since you will have to show you dashboard from creative-tim.com - i.e. sensitive information, you can send us the video on the ticket you have opened on our contact-us form.

Will wait for the asked video.

Best,
Manu
